apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dontstarvetogether.fullname" . }}
  labels:
{{ include "dontstarvetogether.labels" . | indent 4 }}
data:
  {{- range $name, $value := .Values.config }}
  {{- $tp := typeOf $value }}
  {{- if eq $tp "string"}}
  {{ $name | upper }}: {{ $value | quote }}
  {{- else if eq $tp "<nil>"}}
  {{- else if eq $tp "[]interface {}"}}
  {{ $name | upper }}: {{ include "dontstarvetogether.joinListWithComma" $value | quote }}
  {{- else }}
  # {{ $tp }}
  {{ $name | upper }}: {{ $value | toString | quote }}
  {{- end }}
  {{- end }}
