apiVersion: v1
kind: Service
metadata:
  name: {{ include "dontstarvetogether.fullname" . }}
  labels:
{{ include "dontstarvetogether.labels" . | indent 4 }}
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: server
      protocol: UDP
      name: server
  selector:
    app.kubernetes.io/name: {{ include "dontstarvetogether.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
