{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dontstarvetogether.serviceAccountName" . }}
  labels:
{{ include "dontstarvetogether.labels" . | indent 4 }}
{{- end -}}
