apiVersion: v1
kind: Service
metadata:
  name: {{ include "dontstarvetogether.fullname" . }}
  labels:
{{ include "dontstarvetogether.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: server
      protocol: UDP
      name: server
  selector:
    app.kubernetes.io/name: {{ include "dontstarvetogether.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
